<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="BookService"
     targetNamespace="http://benchresources.in/services/BookService/"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
     xmlns:bpws="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
     xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
     xmlns:WL5G3N2="http://benchresources.in/services/BookService/"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
    <plnk:partnerLinkType name="SOAPReference">
        <plnk:role name="IBookService" portType="WL5G3N2:IBookService"/>
    </plnk:partnerLinkType>
    <wsdl:import namespace="http://benchresources.in/services/BookService/" location="BookServicePS.wsdl"/>
</wsdl:definitions>
